// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package micro

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RetStatus int32

const (
	RetStatus_RetStatus_Failure RetStatus = 0
	RetStatus_RetStatus_Success RetStatus = 1
)

var RetStatus_name = map[int32]string{
	0: "RetStatus_Failure",
	1: "RetStatus_Success",
}

var RetStatus_value = map[string]int32{
	"RetStatus_Failure": 0,
	"RetStatus_Success": 1,
}

func (x RetStatus) String() string {
	return proto.EnumName(RetStatus_name, int32(x))
}

func (RetStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

// 返回状态
type CommonRes struct {
	Status               RetStatus `protobuf:"varint,1,opt,name=status,proto3,enum=micro.RetStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CommonRes) Reset()         { *m = CommonRes{} }
func (m *CommonRes) String() string { return proto.CompactTextString(m) }
func (*CommonRes) ProtoMessage()    {}
func (*CommonRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *CommonRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonRes.Unmarshal(m, b)
}
func (m *CommonRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonRes.Marshal(b, m, deterministic)
}
func (m *CommonRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonRes.Merge(m, src)
}
func (m *CommonRes) XXX_Size() int {
	return xxx_messageInfo_CommonRes.Size(m)
}
func (m *CommonRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonRes.DiscardUnknown(m)
}

var xxx_messageInfo_CommonRes proto.InternalMessageInfo

func (m *CommonRes) GetStatus() RetStatus {
	if m != nil {
		return m.Status
	}
	return RetStatus_RetStatus_Failure
}

//  helloReq
type HelloReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReq) Reset()         { *m = HelloReq{} }
func (m *HelloReq) String() string { return proto.CompactTextString(m) }
func (*HelloReq) ProtoMessage()    {}
func (*HelloReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *HelloReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReq.Unmarshal(m, b)
}
func (m *HelloReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReq.Marshal(b, m, deterministic)
}
func (m *HelloReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReq.Merge(m, src)
}
func (m *HelloReq) XXX_Size() int {
	return xxx_messageInfo_HelloReq.Size(m)
}
func (m *HelloReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReq.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReq proto.InternalMessageInfo

func (m *HelloReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HelloReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

//  HelloRes
type HelloRes struct {
	Status               RetStatus `protobuf:"varint,1,opt,name=status,proto3,enum=micro.RetStatus" json:"status,omitempty"`
	Content              string    `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *HelloRes) Reset()         { *m = HelloRes{} }
func (m *HelloRes) String() string { return proto.CompactTextString(m) }
func (*HelloRes) ProtoMessage()    {}
func (*HelloRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *HelloRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRes.Unmarshal(m, b)
}
func (m *HelloRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRes.Marshal(b, m, deterministic)
}
func (m *HelloRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRes.Merge(m, src)
}
func (m *HelloRes) XXX_Size() int {
	return xxx_messageInfo_HelloRes.Size(m)
}
func (m *HelloRes) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRes.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRes proto.InternalMessageInfo

func (m *HelloRes) GetStatus() RetStatus {
	if m != nil {
		return m.Status
	}
	return RetStatus_RetStatus_Failure
}

func (m *HelloRes) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

//  ByeReq
type ByeReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByeReq) Reset()         { *m = ByeReq{} }
func (m *ByeReq) String() string { return proto.CompactTextString(m) }
func (*ByeReq) ProtoMessage()    {}
func (*ByeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *ByeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByeReq.Unmarshal(m, b)
}
func (m *ByeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByeReq.Marshal(b, m, deterministic)
}
func (m *ByeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByeReq.Merge(m, src)
}
func (m *ByeReq) XXX_Size() int {
	return xxx_messageInfo_ByeReq.Size(m)
}
func (m *ByeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ByeReq.DiscardUnknown(m)
}

var xxx_messageInfo_ByeReq proto.InternalMessageInfo

func (m *ByeReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ByeReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

//  ByeRes
type ByeRes struct {
	Status               RetStatus `protobuf:"varint,1,opt,name=status,proto3,enum=micro.RetStatus" json:"status,omitempty"`
	Content              string    `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ByeRes) Reset()         { *m = ByeRes{} }
func (m *ByeRes) String() string { return proto.CompactTextString(m) }
func (*ByeRes) ProtoMessage()    {}
func (*ByeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{4}
}

func (m *ByeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByeRes.Unmarshal(m, b)
}
func (m *ByeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByeRes.Marshal(b, m, deterministic)
}
func (m *ByeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByeRes.Merge(m, src)
}
func (m *ByeRes) XXX_Size() int {
	return xxx_messageInfo_ByeRes.Size(m)
}
func (m *ByeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ByeRes.DiscardUnknown(m)
}

var xxx_messageInfo_ByeRes proto.InternalMessageInfo

func (m *ByeRes) GetStatus() RetStatus {
	if m != nil {
		return m.Status
	}
	return RetStatus_RetStatus_Failure
}

func (m *ByeRes) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterEnum("micro.RetStatus", RetStatus_name, RetStatus_value)
	proto.RegisterType((*CommonRes)(nil), "micro.CommonRes")
	proto.RegisterType((*HelloReq)(nil), "micro.HelloReq")
	proto.RegisterType((*HelloRes)(nil), "micro.HelloRes")
	proto.RegisterType((*ByeReq)(nil), "micro.ByeReq")
	proto.RegisterType((*ByeRes)(nil), "micro.ByeRes")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0x2a, 0x48, 0xd6,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcd, 0x4c, 0x2e, 0xca, 0x57, 0x32, 0xe5, 0xe2,
	0x74, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0x0b, 0x4a, 0x2d, 0x16, 0xd2, 0xe0, 0x62, 0x2b, 0x2e, 0x49,
	0x2c, 0x29, 0x2d, 0x96, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x33, 0x12, 0xd0, 0x03, 0x2b, 0xd2, 0x0b,
	0x4a, 0x2d, 0x09, 0x06, 0x8b, 0x07, 0x41, 0xe5, 0x95, 0x2c, 0xb8, 0x38, 0x3c, 0x52, 0x73, 0x72,
	0xf2, 0x83, 0x52, 0x0b, 0x85, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0xc1, 0x7a, 0x38, 0x83,
	0xc0, 0x6c, 0x21, 0x09, 0x2e, 0xf6, 0xe4, 0xfc, 0xbc, 0x92, 0xd4, 0xbc, 0x12, 0x09, 0x26, 0xb0,
	0x30, 0x8c, 0xab, 0xe4, 0x07, 0xd7, 0x49, 0x82, 0x7d, 0x78, 0xcc, 0x33, 0xe3, 0x62, 0x73, 0xaa,
	0x4c, 0x25, 0xdd, 0x1d, 0x3e, 0x50, 0x7d, 0x54, 0x71, 0x85, 0x96, 0x25, 0x17, 0x27, 0x5c, 0xb9,
	0x90, 0x28, 0x97, 0x20, 0x9c, 0x13, 0xef, 0x96, 0x98, 0x99, 0x53, 0x5a, 0x94, 0x2a, 0xc0, 0x80,
	0x2a, 0x1c, 0x5c, 0x9a, 0x9c, 0x9c, 0x5a, 0x5c, 0x2c, 0xc0, 0x68, 0x14, 0xc5, 0xc5, 0x54, 0x52,
	0x20, 0xa4, 0xc3, 0xc5, 0x11, 0x9c, 0x58, 0x09, 0x0e, 0x19, 0x21, 0x7e, 0xa8, 0x03, 0x60, 0x21,
	0x2c, 0x85, 0x26, 0x50, 0x2c, 0xa4, 0xc6, 0xc5, 0x16, 0x9c, 0x58, 0xe9, 0x54, 0x99, 0x2a, 0xc4,
	0x0b, 0x95, 0x82, 0x84, 0x81, 0x14, 0x0a, 0xb7, 0x38, 0x89, 0x0d, 0x1c, 0xd7, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x19, 0x41, 0x24, 0xdb, 0xf8, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Tp service

type TpClient interface {
	SayHello(ctx context.Context, in *HelloReq, opts ...client.CallOption) (*HelloRes, error)
	SayBye(ctx context.Context, in *ByeReq, opts ...client.CallOption) (*ByeRes, error)
}

type tpClient struct {
	c           client.Client
	serviceName string
}

func NewTpClient(serviceName string, c client.Client) TpClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "micro"
	}
	return &tpClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *tpClient) SayHello(ctx context.Context, in *HelloReq, opts ...client.CallOption) (*HelloRes, error) {
	req := c.c.NewRequest(c.serviceName, "Tp.SayHello", in)
	out := new(HelloRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpClient) SayBye(ctx context.Context, in *ByeReq, opts ...client.CallOption) (*ByeRes, error) {
	req := c.c.NewRequest(c.serviceName, "Tp.SayBye", in)
	out := new(ByeRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Tp service

type TpHandler interface {
	SayHello(context.Context, *HelloReq, *HelloRes) error
	SayBye(context.Context, *ByeReq, *ByeRes) error
}

func RegisterTpHandler(s server.Server, hdlr TpHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Tp{hdlr}, opts...))
}

type Tp struct {
	TpHandler
}

func (h *Tp) SayHello(ctx context.Context, in *HelloReq, out *HelloRes) error {
	return h.TpHandler.SayHello(ctx, in, out)
}

func (h *Tp) SayBye(ctx context.Context, in *ByeReq, out *ByeRes) error {
	return h.TpHandler.SayBye(ctx, in, out)
}
